// <auto-generated />
using System;
using GestionClinicaNutricional.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionClinicaNutricional.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260711042745_InitialMigration13")]
    partial class InitialMigration13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionClinicaNutricional.Domain.ConsultaInicial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Composicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("ConsultaInicial");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanAlimenticioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanAlimenticioId");

                    b.ToTable("Evaluacion");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.HabitoAlimenticio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsultaInicialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaInicialId");

                    b.ToTable("HabitoAlimenticio");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.PlanAlimenticio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsultaInicialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionPlan")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPlan")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSiguienteControl")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaInicialId");

                    b.ToTable("PlanAlimenticio");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.PlanComida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlanAlimenticioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanAlimenticioId");

                    b.ToTable("PlanComida");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.ConsultaInicial", b =>
                {
                    b.HasOne("GestionClinicaNutricional.Domain.Paciente", "Paciente")
                        .WithMany("ConsultaIniciales")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GestionClinicaNutricional.Domain.Antecedente", "Antecedentes", b1 =>
                        {
                            b1.Property<Guid>("ConsultaInicialId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Descripcion")
                                .IsRequired();

                            b1.Property<int>("Problema");

                            b1.HasKey("ConsultaInicialId", "__synthesizedOrdinal");

                            b1.ToTable("ConsultaInicial");

                            b1.ToJson("Antecedentes");

                            b1.WithOwner()
                                .HasForeignKey("ConsultaInicialId");
                        });

                    b.Navigation("Antecedentes");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.Evaluacion", b =>
                {
                    b.HasOne("GestionClinicaNutricional.Domain.PlanAlimenticio", "PlanAlimenticio")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PlanAlimenticioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAlimenticio");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.HabitoAlimenticio", b =>
                {
                    b.HasOne("GestionClinicaNutricional.Domain.ConsultaInicial", "ConsultaInicial")
                        .WithMany("HabitoAlimenticios")
                        .HasForeignKey("ConsultaInicialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaInicial");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.PlanAlimenticio", b =>
                {
                    b.HasOne("GestionClinicaNutricional.Domain.ConsultaInicial", "ConsultaInicial")
                        .WithMany("PlanAlimenticios")
                        .HasForeignKey("ConsultaInicialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaInicial");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.PlanComida", b =>
                {
                    b.HasOne("GestionClinicaNutricional.Domain.PlanAlimenticio", "PlanAlimenticio")
                        .WithMany("PlanComidas")
                        .HasForeignKey("PlanAlimenticioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAlimenticio");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.ConsultaInicial", b =>
                {
                    b.Navigation("HabitoAlimenticios");

                    b.Navigation("PlanAlimenticios");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.Paciente", b =>
                {
                    b.Navigation("ConsultaIniciales");
                });

            modelBuilder.Entity("GestionClinicaNutricional.Domain.PlanAlimenticio", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("PlanComidas");
                });
#pragma warning restore 612, 618
        }
    }
}
