<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>GestionClinicaNutricionalService</RootNamespace>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GestionClinicaNutricional.Application\GestionClinicaNutricional.Application.csproj" />
      <ProjectReference Include="..\GestionClinicaNutricional.Infrastructure\GestionClinicaNutricional.Infrastructure.csproj" />
    </ItemGroup>

</Project>
